/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.catarina.continua3;

/**
 *
 * @author catarina
 */
public class TelaIMC extends javax.swing.JFrame {

    Insert insert = new Insert();
    
    
    public TelaIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        bntCalcularMulher = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bntCalcularHomem = new javax.swing.JButton();
        bntCalcularCrianca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbResultado2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        bntBanco = new javax.swing.JButton();
        lbBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calcule seu IMC");

        bntCalcularMulher.setText("Mulher");
        bntCalcularMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularMulherActionPerformed(evt);
            }
        });

        jLabel3.setText("Qual seu peso?");

        jLabel4.setText("Qual sua altura??");

        bntCalcularHomem.setText("Homem");
        bntCalcularHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularHomemActionPerformed(evt);
            }
        });

        bntCalcularCrianca.setText("Criança");
        bntCalcularCrianca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularCriancaActionPerformed(evt);
            }
        });

        jLabel2.setText("Clique sua classificassão para calcular seu IMC:");

        jLabel5.setText("Cadastre seu email para receber o resultado nele:");

        bntBanco.setText("Enviar");
        bntBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(txtAltura)
                                .addComponent(txtPeso))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntCalcularMulher)
                                .addGap(18, 18, 18)
                                .addComponent(bntCalcularHomem)
                                .addGap(30, 30, 30)
                                .addComponent(bntCalcularCrianca))
                            .addComponent(lbResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBanco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntBanco))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCalcularMulher)
                    .addComponent(bntCalcularHomem)
                    .addComponent(bntCalcularCrianca))
                .addGap(29, 29, 29)
                .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCalcularMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularMulherActionPerformed

        Double peso = Double.parseDouble(txtPeso.getText());
        Double altura = Double.parseDouble(txtAltura.getText());
        CalculoIMC mulherIMC = new MulherIMC(peso, altura);

        Double magreza = mulherIMC.magreza;
        Double normal = mulherIMC.magreza;
        Double obesidade = mulherIMC.magreza;
        Double sobrepeso = mulherIMC.magreza;

        Double imc = (peso / (altura * 2));

        String texto2
                = String.format("seu imc é igual a :%.2f", imc);
        lbResultado.setText(texto2);

        lbResultado2.setText(mulherIMC.mensagem);
    }//GEN-LAST:event_bntCalcularMulherActionPerformed

    private void bntCalcularHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularHomemActionPerformed

        Double peso = Double.parseDouble(txtPeso.getText());
        Double altura = Double.parseDouble(txtAltura.getText());
        CalculoIMC homemIMC = new HomemIMC(peso, altura);

        Double magreza = homemIMC.magreza;
        Double normal = homemIMC.magreza;
        Double obesidade = homemIMC.magreza;
        Double sobrepeso = homemIMC.magreza;

        Double imc = (peso / (altura * 2));

        String texto2
                = String.format("seu imc é igual a :%.2f", imc);
        lbResultado.setText(texto2);

        lbResultado2.setText(homemIMC.mensagem);

    }//GEN-LAST:event_bntCalcularHomemActionPerformed

    private void bntCalcularCriancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularCriancaActionPerformed

        Double peso = Double.parseDouble(txtPeso.getText());
        Double altura = Double.parseDouble(txtAltura.getText());
        CalculoIMC criancaIMC = new CriançaIMC(peso, altura);

        Double magreza = criancaIMC.magreza;
        Double normal = criancaIMC.magreza;
        Double obesidade = criancaIMC.magreza;
        Double sobrepeso = criancaIMC.magreza;

        Double imc = (peso / (altura * 2));

        String texto2
                = String.format("seu imc é igual a :%.2f", imc);
        lbResultado.setText(texto2);

        lbResultado2.setText(criancaIMC.mensagem);
    }//GEN-LAST:event_bntCalcularCriancaActionPerformed

    private void bntBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBancoActionPerformed


        String mensagem = txtBanco.getText();
        
        insert.Inserindo(mensagem);
        
        String texto2
                = String.format("Eviado com sucesso");
        lbBanco.setText(texto2);

   
        

    }//GEN-LAST:event_bntBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBanco;
    private javax.swing.JButton bntCalcularCrianca;
    private javax.swing.JButton bntCalcularHomem;
    private javax.swing.JButton bntCalcularMulher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbBanco;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbResultado2;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
